In [66]:
import pandas as pd

In [67]:
df = pd.read_csv('../data/pokemon_data.csv')
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [68]:
# if you want to replace elemts but only wnat the preview.

df.loc[df['Type 1'] == 'Fire', 'Type 1'].replace('Fire', 'Flamer')

4      Flamer
5      Flamer
6      Flamer
7      Flamer
8      Flamer
42     Flamer
43     Flamer
63     Flamer
64     Flamer
83     Flamer
84     Flamer
135    Flamer
147    Flamer
158    Flamer
169    Flamer
170    Flamer
171    Flamer
236    Flamer
237    Flamer
259    Flamer
263    Flamer
270    Flamer
276    Flamer
277    Flamer
278    Flamer
279    Flamer
352    Flamer
353    Flamer
354    Flamer
355    Flamer
435    Flamer
436    Flamer
437    Flamer
518    Flamer
542    Flamer
557    Flamer
558    Flamer
559    Flamer
572    Flamer
573    Flamer
614    Flamer
615    Flamer
616    Flamer
692    Flamer
721    Flamer
722    Flamer
723    Flamer
730    Flamer
731    Flamer
735    Flamer
736    Flamer
799    Flamer
Name: Type 1, dtype: object

In [69]:
# if you want to change the data frame. with assignments

df.loc[df['Type 1'] == 'Fire', 'Type 1'] = 'Flamer'
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Flamer,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Flamer,Water,80,110,120,130,90,70,6,True

In [70]:
df.loc[df['Type 1'] == 'Flamer'].sample(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
542,485,Heatran,Flamer,Steel,91,90,106,130,106,77,4,True
63,58,Growlithe,Flamer,NaN,55,70,45,70,50,60,1,False
278,257,Blaziken,Flamer,Fighting,80,120,70,110,70,80,3,False
276,255,Torchic,Flamer,NaN,45,60,40,70,50,45,3,False
263,244,Entei,Flamer,NaN,115,115,85,90,75,100,2,True

In [71]:
# turn all the fire/flamer pokemon to legendary
df.loc[df['Type 1'] == 'Flamer', 'Legendary'] = True
df.loc[df['Type 1'] == 'Flamer'].sample(10)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
135,126,Magmar,Flamer,NaN,65,95,57,100,85,93,1,True
353,323,Camerupt,Flamer,Ground,70,100,70,105,75,40,3,True
147,136,Flareon,Flamer,NaN,65,130,60,95,110,65,1,True
542,485,Heatran,Flamer,Steel,91,90,106,130,106,77,4,True
730,662,Fletchinder,Flamer,Flying,62,73,55,56,52,84,6,True
83,77,Ponyta,Flamer,NaN,50,85,55,65,65,90,1,True
572,513,Pansear,Flamer,NaN,50,53,48,53,48,64,5,True
557,498,Tepig,Flamer,NaN,65,63,45,45,45,45,5,True
84,78,Rapidash,Flamer,NaN,65,100,70,80,80,105,1,True
436,391,Monferno,Flamer,Fighting,64,78,52,78,52,81,4,True

# Loading a new checkpoint / restarting the dataframe

In [72]:
df = pd.read_csv('../data/pokemon_data.csv')
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [73]:
# modifying multiple columns

df.loc[df['HP'] > 100, ['Attack', 'Defense']] = ['Big attack', 'Big Defense']
df.loc[df['HP'] > 100]

C:\Users\User\AppData\Local\Temp\ipykernel_31608\927729875.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Big attack' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['HP'] > 100, ['Attack', 'Defense']] = ['Big attack', 'Big Defense']
C:\Users\User\AppData\Local\Temp\ipykernel_31608\927729875.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Big Defense' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['HP'] > 100, ['Attack', 'Defense']] = ['Big attack', 'Big Defense']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
44,39,Jigglypuff,Normal,Fairy,115,Big attack,Big Defense,45,25,20,1,False
45,40,Wigglytuff,Normal,Fairy,140,Big attack,Big Defense,85,50,45,1,False
96,89,Muk,Poison,NaN,105,Big attack,Big Defense,65,100,50,1,False
120,112,Rhydon,Ground,Rock,105,Big attack,Big Defense,45,45,40,1,False
121,113,Chansey,Normal,NaN,250,Big attack,Big Defense,35,105,50,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
753,683,Aromatisse,Fairy,NaN,101,Big attack,Big Defense,99,89,29,6,False
769,699,Aurorus,Rock,Ice,123,Big attack,Big Defense,99,92,58,6,False
792,716,Xerneas,Fairy,NaN,126,Big attack,Big Defense,131,98,99,6,True
793,717,Yveltal,Dark,Flying,126,Big attack,Big Defense,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,108,Big attack,Big Defense,81,95,95,6,True