# Aggregate Statistics

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('../data/pokemon_data.csv')
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

# group by

In [5]:
df.groupby(['Type 1']).mean(numeric_only=True).round()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Bug,334.0,57.0,71.0,71.0,54.0,65.0,62.0,3.0,0.0
Dark,461.0,67.0,88.0,70.0,75.0,70.0,76.0,4.0,0.0
Dragon,474.0,83.0,112.0,86.0,97.0,89.0,83.0,4.0,0.0
Electric,364.0,60.0,69.0,66.0,90.0,74.0,84.0,3.0,0.0
Fairy,450.0,74.0,62.0,66.0,79.0,85.0,49.0,4.0,0.0
Fighting,364.0,70.0,97.0,66.0,53.0,65.0,66.0,3.0,0.0
Fire,327.0,70.0,85.0,68.0,89.0,72.0,74.0,3.0,0.0
Flying,678.0,71.0,79.0,66.0,94.0,72.0,102.0,6.0,0.0
Ghost,486.0,64.0,74.0,81.0,79.0,76.0,64.0,4.0,0.0
Grass,345.0,67.0,73.0,71.0,78.0,70.0,62.0,3.0,0.0
Ground,356.0,74.0,96.0,85.0,56.0,63.0,64.0,3.0,0.0
Ice,424.0,72.0,73.0,71.0,78.0,76.0,63.0,4.0,0.0
Normal,319.0,77.0,73.0,60.0,56.0,64.0,72.0,3.0,0.0
Poison,252.0,67.0,75.0,69.0,60.0,64.0,64.0,3.0,0.0
Psychic,381.0,71.0,71.0,68.0,98.0,86.0,81.0,3.0,0.0
Rock,393.0,65.0,93.0,101.0,63.0,75.0,56.0,3.0,0.0
Steel,443.0,65.0,93.0,126.0,68.0,81.0,55.0,4.0,0.0
Water,303.0,72.0,74.0,73.0,75.0,71.0,66.0,3.0,0.0

In [6]:
#combine the type 1 and type 2
g1 = df.groupby('Type 1').mean(numeric_only=True)
g2 = df.groupby('Type 2').mean(numeric_only=True)

result = g1.add(g2, fill_value=0).round(2)
result

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Bug,716.49,110.22,160.97,150.72,100.54,126.46,123.35,6.55,0.00
Dark,875.20,142.36,198.19,142.28,156.45,139.37,151.51,7.78,0.11
Dragon,956.93,165.48,206.57,173.43,195.34,172.29,163.59,8.04,0.60
Electric,829.17,147.96,141.76,134.63,171.19,147.20,156.00,7.27,0.26
Fairy,828.57,138.42,123.14,139.58,153.53,166.66,109.81,7.68,0.15
Fighting,802.04,149.31,209.62,148.43,134.38,147.09,153.46,7.29,0.15
Fire,809.24,141.15,166.02,147.94,199.40,155.71,154.11,7.21,0.35
Flying,1008.85,142.14,159.04,134.56,169.88,143.71,188.22,8.57,0.63
Ghost,1038.21,123.58,157.92,163.47,152.56,154.54,118.20,8.97,0.13
Grass,850.27,129.91,147.37,150.92,137.66,144.95,119.25,7.84,0.04
Ground,663.88,151.01,185.61,175.16,122.01,129.49,118.56,6.10,0.15
Ice,864.83,162.00,170.75,157.06,170.18,161.08,138.10,7.26,0.30
Normal,1000.17,140.78,126.22,113.60,143.82,127.97,160.80,9.05,0.02
Poison,421.76,126.01,142.27,128.38,134.46,134.30,130.22,4.51,0.00
Psychic,717.96,142.84,146.15,154.71,186.43,173.89,150.98,6.33,0.40
Rock,740.51,133.44,176.86,227.65,114.48,144.05,91.91,6.60,0.09
Steel,878.49,129.86,185.29,231.01,145.25,166.90,114.62,7.67,0.19
Water,703.09,134.78,144.29,158.02,149.31,139.16,123.11,6.29,0.11

In [7]:
df.groupby(['Type 1', 'Type 2']) \
    .mean(numeric_only=True) \
    .sort_index(level=['Type 1', 'Type 2'], ascending=[True, False]).round(2) 
    # sort_index because the types are indexes nnow beacuse wee grouped them by it

                      #      HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
Type 1 Type 2
Bug    Water     283.00   40.00   30.00    32.00    50.00    52.00  65.00
       Steel     416.00   67.71  114.71   112.43    68.14    83.29  63.43
       Rock      442.67   46.67   56.67   146.67    36.67   113.33  35.00
       Poison    199.17   53.75   68.33    58.08    42.50    59.33  65.92
       Ground    351.50   45.50   62.00    97.50    44.50    57.50  38.00
...                 ...     ...     ...      ...      ...      ...    ...
Water  Fighting  452.00   90.67   79.67    91.67   109.33    90.00  95.33
       Fairy     183.50   85.00   35.00    65.00    40.00    65.00  45.00
       Electric  170.50  100.00   48.00    48.00    66.00    66.00  67.00
       Dragon    357.00   82.50  107.50    97.50   122.50   107.50  92.50
       Dark      347.67   69.17  120.00    65.17    88.83    63.50  87.17

                 Generation  Legendary
Type 1 Type 2
Bug    Water           3.00        0.0
       Steel           3.57        0.0
       Rock            4.00        0.0
       Poison          2.33        0.0
       Ground          3.50        0.0
...                     ...        ...
Water  Fighting        3.67        0.0
       Fairy           2.00        0.0
       Electric        2.00        0.0
       Dragon          3.00        0.5
       Dark            3.17        0.0

[136 rows x 9 columns]

In [8]:
df.loc[(df['Type 1'] == 'Bug') & (df['Type 2'] == 'Electric')].mean(numeric_only=True)

#             595.5
HP             60.0
Attack         62.0
Defense        55.0
Sp. Atk        77.0
Sp. Def        55.0
Speed          86.5
Generation      5.0
Legendary       0.0
dtype: float64

In [11]:
df.loc[df['Attack'].astype(str).str.contains(r'12', na=False)].sample(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
689,628,Braviary,Normal,Flying,100,123,75,57,75,80,5,False
114,106,Hitmonlee,Fighting,NaN,50,120,53,35,110,87,1,False
681,620,Mienshao,Fighting,NaN,65,125,60,95,60,105,5,False
443,398,Staraptor,Normal,Flying,85,120,70,50,60,100,4,False
545,487,GiratinaOrigin Forme,Ghost,Dragon,150,120,100,120,100,90,4,True

In [15]:
df['count'] = 1
df.groupby(['Type 1']).count()['count']

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count, dtype: int64

In [18]:
# wwould also add the type 2

df2 = df.copy()

df2['Type'] = df['Type 1']
df3 = df.copy()
df3['Type'] = df['Type 2']

combined = pd.concat([df2, df3])

combined.groupby('Type').size()

Type
Bug          72
Dark         51
Dragon       50
Electric     50
Fairy        40
Fighting     53
Fire         64
Flying      101
Ghost        46
Grass        95
Ground       67
Ice          38
Normal      102
Poison       62
Psychic      90
Rock         58
Steel        49
Water       126
dtype: int64